spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cities
    username: marconemm
    password: 123456
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

#show sql statement
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql: trace